# Generated by Django 5.0.2 on 2024-02-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_restaurant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='mini_image',
            field=models.ImageField(blank=True, default=models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='media'), null=True, upload_to='mini_media'),
        ),
    ]
