# Generated by Django 5.0.2 on 2024-02-19 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_restaurant_mini_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='mini_image',
        ),
    ]
