# Generated by Django 5.0.2 on 2024-02-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_remove_restaurant_mini_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='mini_image',
            field=models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='media_mini'),
        ),
    ]
