# Generated by Django 5.0.2 on 2024-02-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_remove_restaurant_image_restaurant_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='file',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Первая страница меню'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Вторая страница меню'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Третяя страница меню'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='mini_image',
            field=models.ImageField(blank=True, default='media_mini/default.jpg', null=True, upload_to='media_mini/', verbose_name='Фото для миниатюры для общей страницы с ресторанами'),
        ),
    ]
